# Generated by Django 4.1.1 on 2022-09-27 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UNSUBSCRIBED', 'unsubscribed'), ('SUBSCRIBED', 'subscribed')], default='SUBSCRIBED', max_length=100)),
            ],
        ),
    ]
