version: '3'
networks:
  unity:
volumes:
  redis:
services:
  redis:
      image: 'redis:alpine'
      ports:
          - '${FORWARD_REDIS_PORT:-6379}:6379'
      volumes:
          - 'redis:/data'
      networks:
          - unity
      healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
          - '${FORWARD_MAILHOG_PORT:-1025}:1025'
          - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
      networks:
          - unity
  unity:
    build:
      context: ./mindx
      dockerfile: Dockerfile
    ports:
      - '${FORWARD_UNITY_PORT:-8000}:8000'
    environment:
      - 'DJANGO_SETTINGS_MODULE=mindx.settings'
      - 'DJANGO_DEBUG=False'
    volumes:
      - .:/app
    networks:
      - unity
    depends_on:
      - redis
      - mailhog
      - widget
    command: python manage.py runserver 0.0.0.0:8000
  celery:
    build:
      context: ./mindx
      dockerfile: Dockerfile

    volumes:
      - .:/app
    networks:
      - unity
    depends_on:
      - redis
      - mailhog
    command: celery -A mindx worker --beat -l info
  widget:
    image: nginx
    volumes:
    - ./widgets/dist:/usr/share/nginx/html
    - ./default.conf:/etc/nginx/sites-enabled/default
    ports:
    - "8080:80"